---
title: "2. úkol 4EK418"
author: "Jindra Lacko"
format: 
  html:
    self-contained: true
toc: true
execute: 
  eval: true
  echo: true
  message: false
  warning: false
---
  
## Hospody blízké a daleké...
  
Uvažujte dataset pražských hospod jako bodů - kdy hospoda je definována jako amenity typu [bar, pub nebo restaurant](https://wiki.openstreetmap.org/wiki/Key:amenity) - ze zdroje [Open Street Map](https://www.openstreetmap.org/).

Z hospod, barů a restaurací vyberte tu, která je *en*-tá nejbližší od hlavního vchodu k VŠE, definovaným jako adresa `"nám. Winstona Churchilla 1938/4, Praha"` přičemž *en* je poslední (třicátý druhý) znak hashe vašeho jména.

Hash v erku je v šestnáctkové soustavě, nebuďte překvapeni když vám *en* vyjde víc jak 10.

Do mapy prosím zakreslit:

- vchod od VŠE jako bod
- entou nejbližší hospodu jako bod
- kontext, abych se orientoval; může jít o hranice Prahy a řeku Vltavu v případě statického obrázku či vhodnou basemapu v případě dynamického obrázku

```{r}
library(sf)
library(dplyr)
library(osmdata)

# kód pro poslední místo hashe
en <- rlang::hash("Jindra Lacko") %>%
         substr(32, 32) %>%
         strtoi(base = 16)

# zde budiž kód, který: 
# 1) najde pražské hospody + zohlední jejich názvy
# 2) ogeokóduje vchod k VŠE
# 3) spočte vzdálenost hospod a VŠE
# 4) v mapě Prahy ukáže entou nejbližší hospodu od vchodu k VŠE

plot(pressure)

```

Očekávaným výstupem je soubor typu HTML, který uložíte do k tomu zřízené odevzdávárny.

Soubor je napsaný v [Quarto Markdownu](https://quarto.org/) a má ve svém front matter nastavené [execution options](https://quarto.org/docs/computations/execution-options.html) = potlačuje chyby a prosté informace, ale zachovává zobrazení zdrojového kódu.

V komerční praxi může být elegantnější podkladový zdroják potlačit (= nastavit `echo` na `false`), ale pro účely domácího úkolu nechte front matter tak jak je. Váš kód mě zajímá!

Pro zamezení pochybností: soubor jiného typu nežli HTML, ať už `*.R` či tento `*.qmd`, *není* očekávaným výstupem. Prosté obrázky bez kódu *nejsou* očekávaným výstupem, stejně jako kód bez obrázků.