---
title: "2. úkol 4EK418"
author: "Jindra Lacko"
format: 
  html:
    self-contained: true
toc: true
execute: 
  eval: true
  echo: true
  message: false
  warning: false
---

## Hospody blízké a daleké...

Uvažujte dataset pražských hospod jako bodů - kdy hospoda je definována jako amenity typu [bar, pub nebo restaurant](https://wiki.openstreetmap.org/wiki/Key:amenity) - ze zdroje [Open Street Map](https://www.openstreetmap.org/).

Z hospod, barů a restaurací vyberte pouze ty, které ve svém názvu (= sloupec `name`) obsahují vaše iniciály; to znamená že:

- pokud se jmenujete _Jindra Lacko_, tak hledáte řetězec `"jl"`, což je podmínka kterou splňuje například podnik [Špejle](https://www.spejle.eu/) v Jindřišské ulici
- pokud se identifikujete jako _Vladimír Iljič Lenin_, tak hledáte řetězec `"vil"`, a podnik [Green Devil's Absinthe Bar](https://www.greendevils.cz/) za Týnským chrámem.

Pokud žádný podnik vaše iniciály neobsahuje [a umíte to ukázat]{.underline}, tak jako fallback uvažujte všechny.

Z podniků obsahující vaše iniciály vyberte a v mapě města Prahy zakreslete ten, který je nejbližší k (= má nejmenší vzdálenost od) hlavnímu vchodu od VŠE, definovaného jako adresa `"nám. Winstona Churchilla 1938/4, Praha"`.

```{r}
library(sf)
library(dplyr)
library(osmdata)

# zde budiž kód, který: 
# 1) najde pražské hospody + zohlední jejich názvy
# 2) ogeokóduje vchod k VŠE
# 3) spočte vzdálenost vybraných hospod a VŠE
# 4) v mapě Prahy ukáže výsledek = nejbližší hospodu správného jména k VŠE

plot(pressure)

```

Očekávaným výstupem je soubor typu HTML, který uložíte do k tomu zřízené odevzdávárny.

Soubor je napsaný v [Quarto Markdownu](https://quarto.org/) a má ve svém front matter nastavené [execution options](https://quarto.org/docs/computations/execution-options.html) = potlačuje chyby a prosté informace, ale zachovává zobrazení zdrojového kódu.

V komerční praxi může být elegantnější podkladový zdroják potlačit (= nastavit `echo` na `false`), ale pro účely domácího úkolu nechte front matter tak jak je. Váš kód mě zajímá!

Pro zamezení pochybností: soubor jiného typu nežli HTML, ať už `*.R` či tento `*.qmd`, *není* očekávaným výstupem. Prosté obrázky bez kódu *nejsou* očekávaným výstupem, stejně jako kód bez obrázků.
