---
title: "3. úkol 4EK418"
author: "Jindra Lacko"
format: 
  html:
    self-contained: true
toc: true
execute: 
  eval: true
  echo: true
  message: false
  warning: false
knitr:
  opts_chunk:
    out.width: "100%"
---

## Důchodci v Sudetech

Máte dva datasety - pochází ze sčítání lidu v roce 1930 (poslední převálečné) a v roce 1980 (poslední socíkové). Oba bydlí v knihovně [`RCzechia`](https://rczechia.jla-data.net/reference/historie.html).

Prvorepublikový dataset je v členění soudních okresů (n = 330), socíkový dataset je v členění okresů z dob ČSSR (n = 76; pro fanoušky: neexistoval okres Jeseník, Harrachov byl v Semilech).

Z vizualizace se pocitově zdá (a lze matematicky prokázat, což bude předmětem budoucí výuky), že podíl důchodců (definováno jako podíl obvyvatel ve věku 65 let a starších ku celkovému počtu obyvatel přítomných) nebyl v roce 1980 rozdělen po republice rovnoměrně.

Vašim úkolem je vybrat ze dvou alternativních hypotéz tu, která věrněji vysvětluje tento nepoměr:

- hypotéza [Modrých zón](https://en.wikipedia.org/wiki/Blue_zone): tato hypotéza tvrdí, že existují oblasti vyznačující se mimořádnou dlouhověkostí. Příčinou dlouhověkosti je tradiční způsob života, konzumace luštěnin a ořechů a funkční rodinné a společenské vazby. 
Podle hypotézy modrých zód očekáváme, že podíl důchodců v roce 1980 v regionu bude souviset s *podílem důchodců* v témže regionu v roce 1930.

- hypotéza [Postupim](https://en.wikipedia.org/wiki/Potsdam_Agreement): tato hypotéza tvrdí, že po druhé válce proběhly v rámci Československa velké přesuny obyvatelstva. Pohraničí bylo opětovně osidlováno převážně mladými lidmi z vnitrozemí.
Podle hypotézy Postupim očekáváme, že podíl důchodců v roce 1980 v regionu bude souviset s *podílem občanů německé národnosti* v témže regionu v roce 1930.

Oba datasety jsou pro zjednodušení transformovány do souřadnicového systému [ing. Křováka](https://cs.wikipedia.org/wiki/Josef_K%C5%99ov%C3%A1k).

```{r}
library(RCzechia)
library(ggplot2)
library(dplyr)

# census 1980
okresy_1980 <- RCzechia::historie("okresy_1980") %>% 
  mutate(duchodci_80 = `obyvatelstvo celkem 65+` /
           `počet obyvatel přítomných`) %>% 
  select(duchodci_80) %>% 
  st_transform(5514)

# náhled na strukturu
glimpse(okresy_1980)

# census 1930
okresy_1930 <- RCzechia::historie("okresy_1930") %>% 
  mutate(nemci_30 = `národnost německá` /
           `počet obyvatel přítomných`,
         duchodci_30 = `obyvatelstvo celkem věk 65+` /
           `počet obyvatel přítomných` ) %>% 
  select(nemci_30, duchodci_30) %>% 
  st_transform(5514)

# náhled na strukturu
glimpse(okresy_1930)

# obrázek 1980
ggplot() +
  geom_sf(data = okresy_1980, color = NA, aes(fill = duchodci_80)) +
  scale_fill_viridis_c(limits = c(0, .2),
                       option = "magma",
                       direction = -1,
                       na.value = "grey75",
                       labels = scales::label_percent()) +
  labs(title = "Důchodci 1980",
       fill =  "% z celku") +
  theme_minimal()

```

Pro rozhodnutí mezi hypotézami použijte statistické techniky v erku, například lineární regresi + porovnání spočteného R².

Očekávaným výstupem je soubor typu HTML, který uložíte do k tomu zřízené odevzdávárny.

Pro zamezení pochybností:

- soubor jiného typu nežli HTML, ať už `*.R` či tento `*.qmd`, není očekávaným výstupem
- odevzdání jiným způsobem, nežli nahráním souboru do k tomu zřízené odevzdávárny, není očekávávaným způsobem odevzdání